apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: minio
  # deployed yaml
  namespace: ldops-argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fabionns/leap.git'
    path: 03-ldsto/minio/helm/minio-operator
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-development.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ldsto-minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
