apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: minio
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fabionns/leap.git'
    path: 01-ldops/lenses/helm
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-development.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: deepstorage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
